# Konfigurasi untuk aplikasi Laravel
server {
    listen 80;
    server_name kbkuu.hikarva.my.id;
    index index.php index.html;
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# Konfigurasi untuk VS Code (code-server)
server {
    listen 80;
    server_name code-kbkuu.hikarva.my.id;

    location / {
        proxy_pass http://code-server:8443;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
    }
}
